# Generated by Django 4.0.6 on 2022-07-11 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Superpower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['year']},
        ),
    ]
